### ISSUE TITLE
Possibility to leave out keys

### ISSUE THREAD

**Issue by a2** [mczachurski/wallpapper#13]
For example, I don't want the images to depend on the azimuth or altitude, just on dark/light settings. Is that possible for now? I also see that you have to specify `"isForDark": true` and `"isForLight": false` to mark an image for dark mode only.

**Comment by JohnSlaughter** [comment]
Do you want the images to ever change?  Apple has tied this to your location, which is why they use Azimuth and Elevation to determine the sun's position.  (To make sunrise and sunset sync with where you are.) That's why they don't always sync in 1.5 hour intervals. Some of us have shorter days and some have longer days.

If you just want a wallpaper that only works in Dark Mode, only include a single image with generic Az/El data.  It should never change.

**Comment by a2** [comment]
@JohnSlaughter I want a wallpaper (.heic) that changes with light and dark mode. As I said in the original question, I don't understand why all fields are required when I only want a dark/light mode trigger.

**Comment by JohnSlaughter** [comment]
They are required because that’s what Apple designed them to do.  It’s a part of the Dynamic Desktop API.

That said... Are they actually required?  Have you tried this script and omitted them?   And if it does fail, just fake the values and be done with it. You need to generate a JSON file anyway, so you aren’t saving any time leaving it out.

**Comment by a2** [comment]
@JohnSlaughter Thank you for your answer. I was able to use a similar library and when I only set the appearance (dark/light mode) trigger, the file still works. Therefore, I would believe that not all fields _should_ be required. This script _does_ require them, because leaving them out emits a runtime error.

The purpose of this issue is to point out that the keys should be optional (for example, only dependent on azimuth/elevation or only time or only appearance) and that the duplicate "for light" / "for dark" keys are redundant.

**Comment by calebpanza** [comment]
@a2 What is the name of the library that you used? I also want to create a Light Mode/Dark Mode image that is not dependent on Azimuth and Elevation. (also wanna see if the photo works for switching between modes in iOS 13)

**Comment by mczachurski** [comment]
I've added support for wallpapers which are connected with system theme (instead of sun position). Now you can prepare only two images and `json` file which looks like that:

```json
[
    {
        "fileName": "1.png",
        "isPrimary": true,
        "isForLight": true,
        "isForDark": false
    },
    {
        "fileName": "2.png",
        "isPrimary": false,
        "isForLight": false,
        "isForDark": true
    }
]
```

Thanks to this you will have wallpaper which will change when you will switch between system themes.

**Comment by a2** [comment]
@calebpanza I don't recall actually. I recently saw [this blog post](https://harshil.net/blog/dynamic-wallpapers-in-macos-catalina) and [this NSHipster article](https://nshipster.com/macos-dynamic-desktop/) on the matter, though. Hope that helps.

**Comment by calebpanza** [comment]
@mczachurski thanks for updating the package! I've updated and even removed and reinstalled the package, but I keep getting this error for the following json

**JSON**
`[
    {
        "fileName": "Desert1.jpg",
        "isPrimary": true,
        "isForLight": true,
        "isForDark": false
    },
    {
        "fileName": "Desert2.jpg",
        "isPrimary": false,
        "isForLight": false,
        "isForDark": true
    }
]`

**ERROR**
`Reading JSON file: 'file:///Users/caleb.panza/Development/Dump/wallpapper/wallpapper.json'...OK.
Decoding JSON file...Error: type: keyNotFound(CodingKeys(stringValue: "altitude", intValue: nil), Swift.DecodingError.Context(codingPath: [_JSONKey(stringValue: "Index 0", intValue: 0)], debugDescription: "No value associated with key CodingKeys(stringValue: \"altitude\", intValue: nil) (\"altitude\").", underlyingError: nil))`

**Comment by calebpanza** [comment]
@a2 any chance you tried the Light Mode/Dark Mode photos with Catalina??

**Comment by a2** [comment]
@calebpanza Yeah I did. My previous dynamic wallpaper (only light/dark photos) works on Catalina.

**Comment by calebpanza** [comment]
@a2 sorry, I mistyped. I meant to ask if you happened to mimic the new Light Mode/Dark Mode photos on iOS?? That' my end goal with all this, and this seemed the best place to start

**Comment by a2** [comment]
@calebpanza I haven't tried yet with iOS 13

**Comment by mczachurski** [comment]
@calebpanza Sorry I forgot to update homebrew package. Please try again (you should got version 1.3.1).

I copied wallpaper created by application, which has two images (for light and dark theme) to iOS. Unfortunately it's not behave like apple build in wallpapers.

**Comment by calebpanza** [comment]
@a2 @mczachurski I created a new issue to specifically deal with the iOS 13 portion! Really, really hoping that it's possible.

[Issue #35 ](https://github.com/mczachurski/wallpapper/issues/35)
