### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by firexcy** [mczachurski/wallpapper#18]
```
$ wallpapper -i wallpapper.json
dyld: Library not loaded: @rpath/libswiftAVFoundation.dylib
  Referenced from: /usr/local/bin/wallpapper
  Reason: image not found
[1]    38116 abort      wallpapper -i wallpapper.json
```

I have checked the number of pictures and their file names.

**Comment by GoldenChaos** [comment]
I'm also getting this error.

**Comment by JohnSlaughter** [comment]
I got this error from the brew install. I cloned the source and built it myself and it worked fine.

**Comment by JohnSlaughter** [comment]
It’s not your images, trust me.  It’s the linked library not working that is required to load the images. Without it, the app gets no mages, hence the error text.

**Comment by GoldenChaos** [comment]
Solved it by reinstalling wallpaper from homebrew! :D
