### ISSUE TITLE
zsh: command not found: wallpaper

### ISSUE THREAD

**Issue by itsnwa** [mczachurski/wallpapper#2]
Tried switching to bash, but same problem 😞 Any idea?

**Comment by mczachurski** [comment]
Did you execute all steps which are mentioned on repository home page (download code/rebuild/copy executable to bin folder)? If yes, verify that you didn't have any errors and check that you are using proper application name: wallpapper (not wallpaper).

**Comment by tuckerchapin** [comment]
![61724903_1267237283443458_8953486294952968192_n](https://user-images.githubusercontent.com/9058954/58589828-c8c67080-8230-11e9-9d1c-2bc143964437.png)
