### ISSUE TITLE
Automatically compute A and Z based on EXIF

### ISSUE THREAD

**Issue by picnicbob** [mczachurski/wallpapper#20]
It would be pretty great if the altitude and azimuth values could automatically be generated so long as enough EXIF data is present in the input images (timestamp on all + at least one with location).

**Comment by mczachurski** [comment]
I've created separate console application `wallpapper-exif`, it can be used to prepare `JSON` file with Sun location based on `EXIF` metadata from photos. Usage:

```bash
$ wallpapper-exif 1.jpeg 2.jpeg 3.jpeg 4.jpeg
```
