### ISSUE TITLE
Lets share them!

### ISSUE THREAD

**Issue by matimiodosky** [mczachurski/wallpapper#22]
I loved the idea, but as it takes some time to build a nice one, what do you think of assembling something to start shearing the wallpapers?

**Comment by jsmrcaga** [comment]
Make a PR with a `wallpapers` folder containing the first one!

**Comment by matimiodosky** [comment]
What do you mean with PR? @jsmrcaga

**Comment by jsmrcaga** [comment]
@matimiodosky a pull request ;)

**Comment by Kamik423** [comment]
we need that. or a website.

**Comment by red-green** [comment]
Could even just link some in this thread 🤔

**Comment by steven-t-h** [comment]
Anyone made any yet? I'm building out my first now, but it would be great to see some samples.

**Comment by zero298** [comment]
Maybe put that in a separate repository so this code doesn't get bloated when cloned.

**Comment by Kamik423** [comment]
Just putting this here, there *is* a webpage now: [`dynwalls.com`](https://dynwalls.com). They have 6 examples, but you cannot add new ones.

**Comment by mczachurski** [comment]
Also there is: https://wllp.art

**Comment by agirault** [comment]
@mczachurski thanks for the link. They look great, but I can't get them to rotate dynamically for some reason. Any tips?

**Comment by mczachurski** [comment]
@agirault contact with page author (in the footer you have "Contact me" link).
