### ISSUE TITLE
Has anyone come up with a way to change the icon of a heic file in the Desktop selector?

### ISSUE THREAD

**Issue by jjmoody** [mczachurski/wallpapper#25]
Just wondering if anyone knows how to change the icon displayed within the Mac desktop selector screen to an image within your heic file rather than the default Mohave image?

**Comment by WillLangas** [comment]
This seems to be a bug within the Mojave OS. As of right now, there is no way to alter the thumbnail for the dynamic background

**Comment by mczachurski** [comment]
Exactly. It seems that this is an error in Mojave. I hope that Apple will fix it in new OS release.
