### ISSUE TITLE
error: terminated(72): xcrun --sdk macosx --find xctest output:

### ISSUE THREAD

**Issue by mrtnkl** [mczachurski/wallpapper#28]
Got this build error. Turns out it was due to using Xcode Beta. Found the solution here, which was setting the beta to be default:

https://github.com/PerfectlySoft/Perfect/issues/262#issuecomment-405921471

`sudo xcode-select -s /Applications/Xcode-beta.app/Contents/Developer`

Posting it here in case someone else has this issue.

**Comment by dnvriend** [comment]
Thanks, although I had to change it to:

```
sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
```

**Comment by elizabethsiegle** [comment]
Thank you!!
