### ISSUE TITLE
Posterizing in images

### ISSUE THREAD

**Issue by Zonnev** [mczachurski/wallpapper#29]
The output file shows posterizing in images. I use Gimp to create images at 16-bit, there are smooth gradients in those images. Especially in a night sky, gradients aren't smooth anymore in the output file. Is there a way to handle compression of the tiff files better, like no compression?

**Comment by mczachurski** [comment]
I’m adding images with option ‘kCGImageDestinationLossyCompressionQuality’ set to 1.0. According to Apple documentation it should be minimal compression (or lossless compression if destination format supports it): https://developer.apple.com/documentation/imageio/kcgimagedestinationlossycompressionquality. I did not notice any loss of quality on my photos. I don’t know why you’re experiencig that problem.

**Comment by eggsswika** [comment]
Sorry, my English is not good, I wrote it with Google Translate.
I don't know why, no matter what image format I use, there will be problems.
These images seem to have some regular lines on the right side.
But they will be better after dragging the images out of the heic file.

**Comment by mczachurski** [comment]
Cannot reproduce any issues with compression (gradients) in the final images. If issue exists please create new bug.
