### ISSUE TITLE
Building requires Swift 4.2

### ISSUE THREAD

**Issue by LoryB** [mczachurski/wallpapper#3]
Swift 4.2 is only available on Xcode 10 beta... Is there a way to build the console application with the previous Swift version (4.1)? 
Otherwise you should write "Xcode 10 beta required" on instructions
You did an amazing job ;)
P.S. Form application will be better for users in the future imo :)

**Comment by mczachurski** [comment]
Please edit `Package.swift` file. You have to change this line:

```swift
swift-tools-version:4.2
```

to that one:

```swift
swift-tools-version:4.1
```

It's only information for your Swift console tool. The source code is compatible with Swift 4.1 and 4.2.
