### ISSUE TITLE
Error: No such file or directory found during install

### ISSUE THREAD

**Issue by brandondadam** [mczachurski/wallpapper#32]
Hi, I used this tool before in the past, and tried using it again on a new computer. I installed using brew, but keep getting the error attached below.

<img width="941" alt="Screen Shot 2019-04-07 at 11 35 11 PM" src="https://user-images.githubusercontent.com/7631485/55699095-bd706a80-598e-11e9-93c1-e9d6b5116acf.png">

I'm not the most familiar with swift, but is it simply a path issue? It seem like it is looking for the directory: ```.build/x86_64-apple-macosx10.10/release/wallpapper```. Since I am running macosx 10.14.4, would my path change, and therefore need to be updated? I also tried the manual install and got the same issue.

**Comment by mczachurski** [comment]
Hi. It's because of Swift 5 changes. Now it produces executable file in different folder. I fixed ruby homebrew script. You need to run again:

```bash
$ brew update
$ brew install wallpapper
```
