### ISSUE TITLE
Feature: add support for `apple_desktop:h24`

### ISSUE THREAD

**Issue by folletto** [mczachurski/wallpapper#36]
I discovered that there's a second option for dynamic wallpapers, `h24`, which supports `ti`. Would it possible to add support for it? I tried to script it but while I manage to generate it, it doesn't seem to work – I might be missing something.

This means that we have:

* `apple_desktop:solar` with solar info `si` data
* `apple_desktop:h24` with time info `ti` data

The time info data is like this:
```
ti = (
    {
        i = 0;
        t = "0.375";
    },
    ...
);
```

The entry `t` is a decimal conversion of 24 hours, so for example 9:00 = 0.375 (9/24). The `ap` parameter with `l` and `d` seem working as before.

Some wallpapers from Dynamic Wallpaper Club (for example [this](https://dynamicwallpaper.club/wallpaper/hsrdsoah3rp)) use this method, and they work – tested on Mojave 10.14.5. Their online generator is able to generate such wallpapers, as is the [Dynaper](https://dynaperapp.com/) app.

For reference, original discussion via Twitter:
https://twitter.com/Folletto/status/1142600399347736576

**Comment by mczachurski** [comment]
Hi, thank you for all information. I will introduce support of that kind of wallpapers 👍
