### ISSUE TITLE
Finalizing image container...Error: type: wallpapper.ImageFinalizingError

### ISSUE THREAD

**Issue by CodeEagle** [mczachurski/wallpapper#38]
```shell
 wallpapper -i wallpapper.json -o a.heic
Reading JSON file: 'file:///Users/xxx/Desktop/paper/wallpapper.json'...OK.
Decoding JSON file...OK (3 pictures).
Reading image file: 'file:///Users/xxx/Desktop/paper/1.tiff'...OK.
Adding image and metadata...OK.
Reading image file: 'file:///Users/xxx/Desktop/paper/2.tiff'...OK.
Adding image...OK.
Reading image file: 'file:///Users/xxx/Desktop/paper/3.tiff'...OK.
Adding image...OK.
Finalizing image container...Error: type: wallpapper.ImageFinalizingError
```

**Comment by MichaelMKenny** [comment]
This seems to be only an issue on Catalina (Mojave works). It also logs this message out to the console: 

FigPhotoHEIFRotationCCWAndMirroringFromExifOrientation signalled err=-16992 (kFigPhotoError_InternalFailure) (Unsupported orientation value) at /BuildRoot/Library/Caches/com.apple.xbs/Sources/CoreMedia/CoreMedia-2501.6.4.2/Sources/Photo/FigPhotoMetadataUtilities.c:281

I also tried someone else's implementation of dynamic wallpaper generation, and get the same error. Seems to be a bug on Apple's side.

**Comment by beforeold** [comment]
so should we wait for a new release of Catalina to fix this? : (

**Comment by mczachurski** [comment]
On macOS Catalina 10.15 beta 6 (Xcode 11 beta 6) it seems that everything is working.

```bash
Reading JSON file: 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/time-tiff.json'...OK.
Decoding JSON file...OK (4 pictures).
Reading image file: 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/4.tiff'...OK.
Adding image and metadata...OK.
Reading image file: 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/1.tiff'...OK.
Adding image...OK.
Reading image file: 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/2.tiff'...OK.
Adding image...OK.
Reading image file: 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/3.tiff'...OK.
Adding image...OK.
Finalizing image container...OK.
Saving data to file 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/output.heic'...OK.
```

I'm using tiff images compressed as JPEG.

**Comment by beforeold** [comment]
> On macOS Catalina 10.15 beta 6 (Xcode 11 beta 6) it seems that everything is working.
> 
> ```shell
> Reading JSON file: 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/time-tiff.json'...OK.
> Decoding JSON file...OK (4 pictures).
> Reading image file: 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/4.tiff'...OK.
> Adding image and metadata...OK.
> Reading image file: 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/1.tiff'...OK.
> Adding image...OK.
> Reading image file: 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/2.tiff'...OK.
> Adding image...OK.
> Reading image file: 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/3.tiff'...OK.
> Adding image...OK.
> Finalizing image container...OK.
> Saving data to file 'file:///Users/mczachurski/Projects/Wallpepper/earth%20wallpaper/output.heic'...OK.
> ```
> 
> I'm using tiff images compressed as JPEG.

Thanks man, did fixed in Catalina beta 6.

**Comment by dyyybek** [comment]
I have a similar error 10.15.2 xcode 11.3.1
```
Finalizing image container...AVEBridge Info: AVEEncoder_CreateInstance: Received CreateInstance (from VT)
Assert - (remoteService != NULL) - f: /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleAVEBridge/AppleAVEBridge-18/AppleAVEEncoder/AppleAVEEncoder.c l: 290
AVE XPC Error: could not find remote service
Assert - (err == noErr) - f: /BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleAVEBridge/AppleAVEBridge-18/AppleAVEEncoder/AppleAVEEncoder.c l: 1940
AVE ERROR: XPC failed
AVEBridge Info: connectHandler: Device connected (0x00007fd8fdc869d0)AVEBridge Info: stopUserClient: IOServiceClose was successful.

AVEBridge Error: AVEEncoder_CreateInstance: returning err = -12908
```

**Comment by ferdiamg** [comment]
Did you find a fix for issue @dyyybek ? Got the exact same exception on OSX 10.15.3.

**Comment by rudotriton** [comment]
I get the same error, however, it also outputs a `.heic` file with the dynamic wallpaper which actually seems to work perfectly.

**Comment by mczachurski** [comment]
The output file is created despite the `AVEBridge Error` error. `Preview` app reports very similar error when we exporting image to HEIC file. I'm closing the issue since the error is from internal Apple framework and we cannot do anything about it.
