### ISSUE TITLE
"wallpaper" name conflicts with apple's built in wallpaper command

### ISSUE THREAD

**Issue by rob-watts** [mczachurski/wallpapper#39]
I installed wallpaper as per the instructions and can see it in Homebrew:

```bash 
➜  Desktop brew list
composer	inetutils	libidn		node		rpl
fltk		jpeg		libpng		openssl		**wallpaper**
icu4c		lftp		lua		readline
```

When I execute the wallpaper command I get an error:

```bash
➜  Desktop wallpaper -i wallpaper.json

Error: unrecognized option '-I'

```

When I run "wallpaper" I get a different set of command line options..

```bash
➜  Desktop wallpaper

Usage: wallpaper <command> [options]

Manage the desktop wallpaper

Commands:
  set             Set wallpaper image. Usage: set <path>
  get             Get current wallpaper image
  screens         List screens
  help            Prints help information
  version         Prints the current version of this app
```

**Comment by gingerbeardman** [comment]
if `dynamicwallpaper` is too long, then maybe `dynwallpaper` or `dynwall`?

**Comment by rob-watts** [comment]
Nah, ```dynamicwallpaper``` is perfect, it says what it is. What about ```makewallpaper```?

**Comment by mczachurski** [comment]
Installation instructions from readme page:

```
brew tap mczachurski/wallpapper
brew install wallpapper
```

Thus the name of the application is: `wallpapper` (with two p letters).

**Comment by rob-watts** [comment]
ahhh.. that was it. I didn't notice the extra p and I did a brew install wallpaper and got something else. I have it working now.
thanks

**Comment by gingerbeardman** [comment]
I also missed the extra p 😂
