### ISSUE TITLE
Outputs a "blank" heic file

### ISSUE THREAD

**Issue by KabirKwatraAlt** [mczachurski/wallpapper#4]
working with many large pngs..
json is fine, but when wallpapper is run it outputs a heic file with zero KB file size..
is there a mix file size?

**Comment by mczachurski** [comment]
Can you provide more information:
 - how big are your files?
 - did you get errors on console (did you try debug the code)?
 - what hardware do you have (especially RAM)?
 
Can you send me the file (or link to file/files) - I will try to reproduce the bug?

**Comment by alicerunsonfedora** [comment]
I'm getting this same error, too. I have files that are 2560 × 1440 (12 files total, ~2.5 MB each). I have no errors in the console as shown (no debug, though).

<img width="602" alt="screen shot 2018-07-28 at 10 37 11 am" src="https://user-images.githubusercontent.com/13445064/43357603-32c16280-9252-11e8-9810-f29562e611fb.png">

I have a base MacBook Pro 2017 (no Touch Bar). These are the contents of the folder.

<img width="1014" alt="screen shot 2018-07-28 at 10 39 21 am" src="https://user-images.githubusercontent.com/13445064/43357619-7eee3494-9252-11e8-9571-f170a727fd4e.png">

There's one thing I have left to try, though...

**Comment by alicerunsonfedora** [comment]
Just found out you need 16 images. My problem's solved. Do you have 16 images for yours, @KabirKwatraAlt ?

**Comment by mczachurski** [comment]
Great investigation! I founded error in the source code and I fixed it. Now you can produce HEIC images with different number of images. However, it seems that Apple supports only wallpapers with 16 images (I tried with 24 images and they didn't change).

Please let me know if the fix solves your issues.
