### ISSUE TITLE
Reverse engineer .heic to files and .json

### ISSUE THREAD

**Issue by habovh** [mczachurski/wallpapper#45]
Hi,

This tool is really convenient and works quite well.

In my case, I have a dual screen setup but wanted to use the default Big Sur wallpaper to span across my displays and remain dynamic.

So I eventually extracted still frames, cropped them, and generated dynamic heic from these images. The only thing I'm missing is the original images azimuth/angle settings, so I kind of eyeballed them in the JSON and it got me a pretty close-to-original experience, however it's not quite there yet.

I was wondering, how hard would it be for this tool that can generate dynamic HEIC files to extract azimuth data from an existing one? That would be pretty dope IMO!

Thoughts on this?

**Comment by mczachurski** [comment]
Hi,

I've implemented extracting metadata from existing HEIC files. You need to download 1.6.0 version (`brew upgrade mczachurski/wallpapper/wallpapper`) and run following command:

```bash
$ wallpapper -e YOURFILE.heic
```

**Comment by habovh** [comment]
Wow that was quick! Thanks dude! Can confirm it works perfectly for my use case! 🎉

You sir are an example to us all open source developers.
