### ISSUE TITLE
Brew install fails on arm64

### ISSUE THREAD

**Issue by foxnne** [mczachurski/wallpapper#46]
After installing latest Xcode (full IDE from App Store) and following the instructions on the readme I get an error:

`==> Installing wallpapper from mczachurski/wallpapper`
`==> Downloading https://github.com/mczachurski/wallpapper/archive/1.6.0.tar.gz`
`Already downloaded: /Users/foxnne/Library/Caches/Homebrew/downloads/f4b290acb31335cc1f06a5c07f5dfb3cb756fabe4241edcbded2b8e198a4138f--wallpapper-1.6.0.tar.gz`
`==> swift build --disable-sandbox --configuration release`
`Error: An exception occurred within a child process:
  Errno::ENOENT: No such file or directory - ./.build/x86_64-apple-macosx/release/wallpapper`

Just an issue for arm64, built fine from repo just needed to change last command to `sudo cp ./.build/arm64-apple-macosx/release/wallpapper`

**Comment by mczachurski** [comment]
I've updated the homebrew script (now instead `x86_64-apple-macosx` directory it uses `release` symlink). Could you verify this bug (I don't have ARM Mac)?

**Comment by foxnne** [comment]
Works fine now! Thank you!
