### ISSUE TITLE
Unexpected error while finalizing image

### ISSUE THREAD

**Issue by hpohlmeyer** [mczachurski/wallpapper#49]
I am trying to create a light/dark wallpaper with two solid colors.
Both of my images are 1px × 1px, but during the image creating, I am getting the following error:

```
Reading JSON file: 'file:///Users/henno/Desktop/wallpapper.json'...OK.
Decoding JSON file...OK (2 pictures).
Reading image file: 'file:///Users/henno/Desktop/dark.png'...OK.
Adding image and metadata...OK.
Reading image file: 'file:///Users/henno/Desktop/light.png'...OK.
Adding image...OK.
Finalizing image container...Error: Unexpected error occurs: Image has not be finilized.
```

The console output for wallpapper looks like this:

<img width="1690" alt="grafik" src="https://user-images.githubusercontent.com/6564077/117341542-8be66800-aea2-11eb-8be0-2d2005ace1d6.png">

Here are the png and json files:
[solid-color-wallpaper.zip](https://github.com/mczachurski/wallpapper/files/6436656/solid-color-wallpaper.zip)

Versions:
- MacOS: 11.2.3
- Swift: 5.4
- Xcode: 12.5
- wallpapper: 1.7.1 (installed through brew)

**Comment by mczachurski** [comment]
Hi, I don't know. Unfortunately Apple didn't provide any information about that macOS feature.
