### ISSUE TITLE
ISO 8601 timings not working for wallpaper

### ISSUE THREAD

**Issue by Hydrochloric-Acid168** [mczachurski/wallpapper#54]
So I've been trying to make a wallpaper using the time based script and the timings for the ISO 8601 format are just not working. For Example, it displays the sunset image at 12:00 AM my time. will leave my code down below. 
`[
    {
        "fileName": "Dawn.png",
        "isPrimary": true,
        "isForLight": true,
        "time": "2021-08-10T15:00:00Z"
    },
    {
        "fileName": "Sunrise.png",
        "time": "2021-08-10T16:00:00Z"
    },
    {
        "fileName": "Noon.png",
        "time": "2021-08-10T22:00:00Z"
    },
    {
        "fileName": "Afternoon.png",
        "time": "2021-10-10T02:00:00Z"
    },
    {
        "fileName": "Sunset.png",
        "time": "2021-08-10T04:00:00Z"
    },
    {
        "fileName": "Evening.png",
        "time": "2021-08-10T05:00:00Z"
    },
    {
        "fileName": "Night.png",
        "isForDark": true,
        "time": "2021-08-10T08:00:00Z"
    }
]
`

**Comment by ic0056** [comment]
Instead of using the UTC time directly, I have success appending the offset for my time zone, i.e. "time":"2021-10-10T02:00:00-05:00"

**Comment by Hydrochloric-Acid168** [comment]
do you have to append the Z marker at the end of the time string still? I was quite unsure about that

**Comment by Hydrochloric-Acid168** [comment]
Ok so for the people looking upon this issue, it seems that it might not be clear to most people about how to time wallpapers properly. For the wallpapers to work properly, you need to Offset the Universal Coordinated Time (UTC) by your time zone's offset (EG. offset for Los Angeles is 7 hours, so the time format at 5:00 AM for LA would be "2021-09-26T05:00:00-07:00" in the editor. To calculate the offset easily, I used this website:
https://www.timestamp-converter.com
I hope this helps out with the wallpapers!

**Comment by BartmanEH** [comment]
Timezone offset is not constant all year around for most timezones--Daylight Savings Time still plagues us. How do we overcome the offset changing twice a year? Arguably a difference of one hour is not critical.

**Comment by ic0056** [comment]
I actually have not try using local time, i.e. without the Z. Maybe that would work.
