### ISSUE TITLE
Using local time for time changing wall paper

### ISSUE THREAD

**Issue by Kile** [mczachurski/wallpapper#59]
Hi, this was asked in the comments of #54 already, but I was wondering if it is possible to use the local pc time for the wallpaper that changed based on what time it is and if so how. 

If this is not possible yet I would love this functionality to be added.
Cheers.

**Comment by V4G4X** [comment]
You can, just use your timezone's offset instead of the `Z` in the timestamp.

For example:
I want the timestamp of 5PM, 22 July 2022 IST. IST is 5:30 hours ahead of UTC/GMT.  
So I'd use this timestamp: `2022-07-22T17:00:00+05:30`. 
The format being: `<DATE>T<HH>:<MM>:<SS>+<OFFSET>`

**Comment by Kile** [comment]
Thank you
