### ISSUE TITLE
Error using "wallpaper -h" command 

### ISSUE THREAD

**Issue by RoguePlayer** [mczachurski/wallpapper#6]
I followed the directions in order and was unable to run "wallpapper -h". I was able to open the directory and run the command that was but there was no use because it immediately exits. Is there anything I did wrong?  I am using the current 4.2 version of swift. When you say run "wallpaper -h" in console, do you you mean in terminal? I have been trying to run it through terminal and have been getting a "command not found" error. Would it be possible to get a video guide for this program?

**Comment by mczachurski** [comment]
You can try install the application via Homebrew (I added instructions on main page of the repository). Maybe this will help. From your description I cannot deduce if you did something wrong. If you will have still problems, wrote exactly here commands which you are executing with their responses.

**Comment by dingsdiggy** [comment]
I do have this issue as well and installing homebrew was no help, all I get is "command not found"

I tried installing by running the install-codelines at once or one after another, at some point my terminal line starts with username/wallpapper but i cant run any command? All it says is command not found
