### ISSUE TITLE
Brew install fails

### ISSUE THREAD

**Issue by tollfree** [mczachurski/wallpapper#61]
Brew install fails:

> Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force
If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install
Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 13.3.

Installed Command Line Tools 13.3.1 are the last ones available.
MacOS version is 12.3.1.

**Comment by mczachurski** [comment]
Cannot reproduce. Maybe it's issue for brew toolset.
