### ISSUE TITLE
The HEIC set to wallpaper doesn't change with time and shows wrong frame

### ISSUE THREAD

**Issue by V4G4X** [mczachurski/wallpapper#65]
I have the following json:
```
[
    {
        "fileName": "kimi no nawa-1.jpg",
        "isPrimary": true,
        "time": "2022-07-21T07:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-2.jpg",
        "isForDark": true,
        "time": "2022-07-21T00:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-3.jpg",
        "time": "2022-07-21T08:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-4.jpg",
        "time": "2022-07-21T09:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-5.jpg",
        "isForLight": true,
        "time": "2022-07-21T10:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-6.jpg",
        "time": "2022-07-21T11:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-7.jpg",
        "time": "2022-07-21T12:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-8.jpg",
        "time": "2022-07-21T15:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-9.jpg",
        "time": "2022-07-21T17:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-10.jpg",
        "time": "2022-07-21T18:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-11.jpg",
        "time": "2022-07-21T019:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-12.jpg",
        "time": "2022-07-21T21:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-13.jpg",
        "time": "2022-07-21T21:30:00+05:30"
    },
    {
        "fileName": "kimi no nawa-14.jpg",
        "time": "2022-07-21T22:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-15.jpg",
        "time": "2022-07-21T23:00:00+05:30"
    },
    {
        "fileName": "kimi no nawa-16.jpg",
        "time": "2022-07-21T23:30:00+05:30"
    }
]
```
As you can see `isPrimary`, `isForDark` and `isForLight` are only for one frame each.  
Another thing to note is the `+05:30` in the timestamps(My attempt at using my local timezone).  

The odd behaviour:
- Even during the day(as I write this) it shows only the one set as `isForDark`. 
- The wallpaper changes only if I change from dark mode to light mode. But **NOT** the one set as `isForLight`.
- The System Preferences application bugs out and shows overlapped text. <img width="364" alt="Screenshot 2022-07-21 at 13 18 30" src="https://user-images.githubusercontent.com/34249137/180160201-055ae00e-defe-444c-954b-32cf42a05479.png">

Things I've tried:
- Using the solar method, same issue. Didn't work.
- Removing `isPrimary`, `isForDark` and `isForLight` completely. Then the System Preferences application stops bugging out.
<img width="441" alt="image" src="https://user-images.githubusercontent.com/34249137/180161315-38c125e8-609d-4df9-a12e-34fca874d242.png">

But it still doesn't show the Dynamic/Still options the way the stock wallpapers do:
<img width="554" alt="image" src="https://user-images.githubusercontent.com/34249137/180161475-34090652-2f16-4ff3-90d2-c4721e0e3adc.png">

I have a MacBook Pro (13-inch, M1, 2020).

**Comment by V4G4X** [comment]
Incase you were wondering, the generated wallpaper shows the following options:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/34249137/180161835-5ea63852-9417-442b-a30e-f455aeba33ca.png">


The solarJson is as follow(In case you were curious):
```
[
    {
        "fileName": "kimi no nawa-1.jpg",
        "isPrimary": true,
        "altitude": 10.6,
        "azimuth": 71.74
    },
    {
        "fileName": "kimi no nawa-2.jpg",
        "isForDark": true,
        "altitude": -49.58,
        "azimuth": 344.87
    },
    {
        "fileName": "kimi no nawa-3.jpg",
        "altitude": 24.18,
        "azimuth": 75.28
    },
    {
        "fileName": "kimi no nawa-4.jpg",
        "altitude": 38.00,
        "azimuth": 78.11
    },
    {
        "fileName": "kimi no nawa-5.jpg",
        "isForLight": true,
        "altitude": 51.96,
        "azimuth": 80.25
    },
    {
        "fileName": "kimi no nawa-6.jpg",
        "altitude": 65.99,
        "azimuth": 81.25
    },
    {
        "fileName": "kimi no nawa-7.jpg",
        "altitude": 80.00,
        "azimuth": 77.43
    },
    {
        "fileName": "kimi no nawa-8.jpg",
        "altitude": 57.43,
        "azimuth": 279.10
    },
    {
        "fileName": "kimi no nawa-9.jpg",
        "altitude": 29.54,
        "azimuth": 283.46
    },
    {
        "fileName": "kimi no nawa-10.jpg",
        "altitude": 15.83,
        "azimuth": 286.70
    },
    {
        "fileName": "kimi no nawa-11.jpg",
        "altitude": 2.57,
        "azimuth": 290.76
    },
    {
        "fileName": "kimi no nawa-12.jpg",
        "altitude": -23.19,
        "azimuth": 302.91
    },
    {
        "fileName": "kimi no nawa-13.jpg",
        "altitude": -29.01,
        "azimuth": 307.31
    },
    {
        "fileName": "kimi no nawa-14.jpg",
        "altitude": -34.46,
        "azimuth": 312.52
    },
    {
        "fileName": "kimi no nawa-15.jpg",
        "altitude": -43.78,
        "azimuth": 326.12
    },
    {
        "fileName": "kimi no nawa-16.jpg",
        "altitude": -47.29,
        "azimuth": 334.82
    }
]
```

**Comment by V4G4X** [comment]
The cyberpunk and Earth one who've added in your readme do work.  
And they have a description for dynamic too:

<img width="575" alt="image" src="https://user-images.githubusercontent.com/34249137/180166900-d96095b1-5352-4203-adbd-6c54bb54b065.png">

**Comment by Macintosh-Fan** [comment]
Not guaranteed to work:
Try changing to an Apple default wallpaper, and set it to dynamic. Once done, load in your dynamic wallpaper (I use the services option in Finder with right-click, and set wallpaper).

**Comment by V4G4X** [comment]
So my bad. The time based wallpaper changes exactly as per it's values. It however was not working well by changing the clock, so I was confused.  

The solar coordinated wallpapers also work, but their timings is very off. If the sunset is at 6PM, then sunset frame will have an altitude of around 0 degrees.  
But that frame will be set at around 4PM instead.  
It's weird.

But closing this issue for the reason that they actually work.
