### ISSUE TITLE
Error: 'wallpapper.InputFileNotExistsError'.

### ISSUE THREAD

**Issue by GoldenChaos** [mczachurski/wallpapper#8]
Finally got the json file made, but when attempting to run `wallpaper -i filename.json` I get the following error :

`Error: 'wallpapper.InputFileNotExistsError'.`

I'm on Mojave DP5. The json file is definitely in the folder with the rest of the images and I'm referencing it with the correct name. In addition, I double checked all the files referenced in the json file and they are correctly named, too.

**Comment by mczachurski** [comment]
I cannot replicate this. I added more information to the console log. Please grab new source code and execute it. You should get more information on console. Maybe this will help us with this bug.

**Comment by GoldenChaos** [comment]
Cool, I should have some time to do this tomorrow 🙂

**Comment by vinivendra** [comment]
I got the same problem, fixed it by renaming the folder I was in into something without spaces.

**Comment by GoldenChaos** [comment]
Finally got the chance to try this again. Removing spaces from the names of my folders did not fix the issue. Here's a screenshot of my terminal:

<img width="682" alt="screen shot 2018-08-10 at 5 15 41 pm" src="https://user-images.githubusercontent.com/1396727/43981748-16d866bc-9cc1-11e8-97e6-efaea8007a74.png">

**Comment by mczachurski** [comment]
Thanks for your feedback. I added support for absolute paths. It's working with paths with spaces:

```bash
wallpapper -i /Users/mczachurski/Projects/Wallpepper/earth\ wallpaper/wallpaper.json
```

and without spaces. Also relative paths works:

```bash
wallpapper -i earth/wallpapper.json
```

Please verify my fix.

**Comment by GoldenChaos** [comment]
I can confirm it worked! 😄 this is awesome.

By the way, the reason I wanted to use the Solar Gradients JSON data is because I started with it as a template and worked backwards to recolor various photos to look like different times of day according to the Solar Gradients wallpaper. It looks perfect!
