### ISSUE TITLE
HEIC file showing up with zero bytes

### ISSUE THREAD

**Issue by levikline** [mczachurski/wallpapper#9]
I did everything I was instructed to do, and the output file returns with nothing in it.

**Comment by mczachurski** [comment]
This issue is very similar to that one: #4. Are you sure that you are using newest source code? Which macOS/XCode/Swift are you using?

**Comment by levikline** [comment]
I didn't download anything, I just followed the terminal commands you have written including copying the git repo. So I am assuming that code uses the latest one. I am on osx mojave and running Xcode GM (i think 9.4 or so) and Swift 4.1

**Comment by levikline** [comment]
Any ideas?

**Comment by mczachurski** [comment]
From your description it's hard to figure out what is wrong.

Verify json file (especially file names, number of pictures/nodes in json etc.). Write here all commands which you are executing with their responses. Also you can attach your `json` file here (and pictures).  

If you are developer and you know how to debug the source code, you can run following command:

```bash
swift package generate-xcodeproj
```

This command will generate new Xcode project. Then you can open that project in Xcode and you can run and debug the code (of course you have to set correct parameters).

**Comment by levikline** [comment]
It won't let me upload the photos because they are each more than 12mb and the JSON file can't upload because of its format so I will paste it below. I typed in the exact same commands as your git page uses in the same order.

[
  {
    "fileName": "1.png",
    "isPrimary": true,
    "isForLight": true,
    "isForDark": false,
    "altitude": 21.84,
    "azimuth": 82.90
  },
  {
    "fileName": "2.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": 46.53,
    "azimuth": 100.56
  },
  {
    "fileName": "3.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": 68.58,
    "azimuth": 136.73
  },
  {
    "fileName": "4.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": 68.82,
    "azimuth": 222.27
  },
  {
    "fileName": "5.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": 34.54,
    "azimuth": 268.63
  },
  {
    "fileName": "6.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": 13.01,
    "azimuth": 282.59
  },
  {
    "fileName": "7.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": -4.70,
    "azimuth": 294.89
  },
  {
    "fileName": "8.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": -15.53,
    "azimuth": 304.43
  },
  {
    "fileName": "9.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": -25.01,
    "azimuth": 315.84
  },
  {
    "fileName": "10.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": -32.54,
    "azimuth": 329.73
  },
  {
    "fileName": "11.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": -37.22,
    "azimuth": 346.23
  },
  {
    "fileName": "12.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": -38.26,
    "azimuth": 4.29
  },
  {
    "fileName": "13.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": -34.20,
    "azimuth": 25.93
  },
  {
    "fileName": "14.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": -25.31,
    "azimuth": 43.84
  },
  {
    "fileName": "15.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": false,
    "altitude": -10.65,
    "azimuth": 60.32
  },
  {
    "fileName": "16.png",
    "isPrimary": false,
    "isForLight": false,
    "isForDark": true,
    "altitude": 6.65,
    "azimuth": 73.35
  }
]

**Comment by levikline** [comment]
Fixed by making file sizes smaller
